# Generated by Django 3.1.6 on 2023-02-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('decsription', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('etat', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('prix_vente', models.CharField(max_length=300)),
                ('etat', models.CharField(max_length=300)),
                ('quantite_disponible', models.DecimalField(decimal_places=2, max_digits=5)),
                ('decsription', models.CharField(max_length=300)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.produit')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.user'),
        ),
    ]
